name: facelocker_tablet
description: Tablet app for FaceLocker
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  mqtt_client: ^10.2.1
  http: ^1.2.2
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.10.4
  collection: ^1.18.0
  image_picker: ^1.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
